driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[apt-repo]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[apt-repo]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[apt-repo]

suites:
  - name: mroonga
    run_list:
      - recipe[mroonga]
