language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
bundler_args: --full-index --jobs=2 --without integration development
cache:
  - bundler
script:
  - bundle ex rake travis
notifications:
  email:
    on_success: never  # default: change
    on_failure: always # default: always
